k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  crumbsless: false
  readOnly: false
  noIcons: false
  ui:
    enableMouse: true
    headless: false
    logoless: false
    reactive: true
    skin: dracula_skin
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: sso-eks-live-admin
  currentCluster: arn:aws:eks:eu-west-1:835487002321:cluster/platform-live-eks
  clusters:
    arn:aws:eks:eu-west-1:206125371300:cluster/platform-staging-eks:
      namespace:
        active: consumer-core
        favorites:
        - consumer-core
        - payments
        - platform
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    arn:aws:eks:eu-west-1:835487002321:cluster/platform-live-eks:
      namespace:
        active: consumer-core
        favorites:
        - consumer-core
        - payments
        - platform
        - default
      view:
        active: deployments
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
