import = ["~/.config/alacritty/night-owl.toml"]
[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[bell]
animation = "Linear"
duration = 500
color = "#b59b9c"

[terminal]
osc52 = "CopyPaste"

[window]
opacity = 0.80
decorations_theme_variant = "Dark"
dynamic_padding = false

[window.padding]
x = 25
y = 20
