[[snippets]]
  description = "Check health of local CPS"
  command = "curl -X GET http://localhost:8000/health"
  output = ""

[[snippets]]
  description = "Order Status Paid Consumer Log Raw"
  command = "stern -n consumer-core customer-plans-service-order-status-paid-consumer"
  output = ""

[[snippets]]
  description = "lazydocker"
  command = "lazydocker"
  output = ""

[[snippets]]
  description = "process orchestrator cli"
  command = "kubectl exec -it $(kubectl get pods -A -l app=process-orchestrator-cli --namespace consumer-core --no-headers | awk '{print $2}') -- bash"
  output = ""

[[snippets]]
  description = "Kafka Connect Status"
  command = "curl https://kafka-connect-orders-stream-processors.<env=live>-k8s.hellofresh.io/connectors/orders-stream-processors.cdc.<country_code=us>/status | jq ."
  output = ""

[[snippets]]
  description = "Intfood RDS passwords"
  command = "vault read <env=live>/intfood/terraform/rds | grep <user=readonly>"
  output = ""

[[snippets]]
  description = "connector status"
  command = "https https://kafka-connect-orders-stream-processors-<id=1>.live-k8s.hellofresh.io/connectors?expand=info&expand=status | jq '. | to_entries[] | [ .value.info.type, .key, .value.status.connector.state,.value.status.tasks[].state,.value.info.config.\"connector.class\"]|join(\":|:\")' | column -s : -t| sed 's/\\\"//g'| sort"
  output = ""
